version: "3.7"

# 컴퓨터들
services:
  my-backend: # 컴퓨터 이름
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  my-databse: # 컴퓨터 이름
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"
